export const ADD_CHARACTER = 'ADD_CHARACTER';

export const UPDATE_CLASS = 'UPDATE_CLASS';
export const UPDATE_RACE = 'UPDATE_RACE';
export const UPDATE_PLAYERNAME = 'UPDATE_PLAYERNAME';

export const UPDATE_ABILITY = 'UPDATE_ABILITY';

export const UPDATE_SKILL = 'UPDATE_SKILL';

export const UPDATE_MONEY = 'UPDATE_MONEY';

export const UPDATE_HP = 'UPDATE_HP';
export const UPDATE_TEMP_HP = 'UPDATE_TEMP_HP';
export const UPDATE_ARMORCLASS = 'UPDATE_ARMORCLASS';
export const UPDATE_SPEED = 'UPDATE_SPEED';
export const UPDATE_INITIATIVE = 'UPDATE_INITIATIVE';

export const ADD_EQUIPMENT = 'ADD_EQUIPMENT';
export const REMOVE_EQUIPMENT = 'REMOVE_EQUIPMENT';
export const UPDATE_EQUIPMENT = 'UPDATE_EQUIPMENT';

export const ADD_WEAPONS_SPELLS = 'ADD_WEAPONS_SPELLS';
export const REMOVE_WEAPONS_SPELLS = 'REMOVE_WEAPONS_SPELLS';
export const UPDATE_WEAPONS_SPELLS = 'UPDATE_WEAPONS_SPELLS';
